#!/bin/bash

# The idea here is to merge all the individual CSVs that contain an image pair's values, as generated by
# plot_two_tiles.py

#TODO consider combining this script with ./merge_csvs.sh for simplicity

tiles="h08v05 h09v04 h11v04 h11v09 h12v04 h16v02 h26v04 h30v11"
m_bands="Band1 Band2 Band3 Band4 Band5 Band6 Band7 vis nir shortwave"
v_bands="M3 M4 M5 M7 M8 M10 M11"
product='A4'

#TODO add cmd option to specify the comparison type, ie either MODIS-VIIRS or VIIRS-VIIRS, since
#it determines which set of bands to iterate over

#for m_band in ${m_bands};
#do    
#    for tile in ${tiles};
#    do   
#	./merge_csvs.sh /ipswich/data02/arthur.elmes/comparo_results/csv/${tile}/MCD_VNP/${product}/${m_band}/ /ipswich/data02/arthur.elmes/comparo_results/csv/${tile}/${tile}_MCD_VNP_2019_all_nbar_only_${m_band}.csv
#	./merge_csvs.sh /ipswich/data02/arthur.elmes/comparo_results/csv/${tile}/MCD_VJ1/${product}/${m_band}/ /ipswich/data02/arthur.elmes/comparo_results/csv/${tile}/${tile}_MCD_VJ1_2019_all_nbar_only_${m_band}.csv
#    done
#done

for v_band in ${v_bands};
do  
    for tile in ${tiles};
    do   
	./merge_csvs.sh /ipswich/data02/arthur.elmes/comparo_results/csv/${tile}/VJ1_VNP/${product}/${v_band}/ /ipswich/data02/arthur.elmes/comparo_results/csv/${tile}/${tile}_VJ1_VNP_2019_all_nbar_only_${v_band}.csv
    done
done
